// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNWgUpReok9a_8yS5FAygyyqBmEBK6d7c',
    appId: '1:808424343220:web:c9494decc92d274788f9e1',
    messagingSenderId: '808424343220',
    projectId: 'bismillahbisa1234',
    authDomain: 'bismillahbisa1234.firebaseapp.com',
    storageBucket: 'bismillahbisa1234.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCESE3GRNGdHh6yV2gcTPT6Mk1DDmWNNV4',
    appId: '1:808424343220:android:446379401a089cca88f9e1',
    messagingSenderId: '808424343220',
    projectId: 'bismillahbisa1234',
    storageBucket: 'bismillahbisa1234.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY1PrdVGHKwRp-WDM-17tgXQDD597iFrE',
    appId: '1:808424343220:ios:9e0550bc9f4154d088f9e1',
    messagingSenderId: '808424343220',
    projectId: 'bismillahbisa1234',
    storageBucket: 'bismillahbisa1234.appspot.com',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY1PrdVGHKwRp-WDM-17tgXQDD597iFrE',
    appId: '1:808424343220:ios:ebdc42a79996f2cf88f9e1',
    messagingSenderId: '808424343220',
    projectId: 'bismillahbisa1234',
    storageBucket: 'bismillahbisa1234.appspot.com',
    iosBundleId: 'com.example.firebaseAuthentication.RunnerTests',
  );
}
